###################
### exp14_2_loc_dust2
###################
debug: False

### model
is_multi_task: True
is_multi_task_balanced: False
task_mix_ratio: 1.0

# Exp14_2_loc_dust2: current 224 + short-instruction + LoRA loc-only dust2 baseline.
alpha_loc_loss: 1.0

is_loc_aux_loss: False
is_aux_loc_em_loss: False
is_aux_loc_uncertainty_loss: False
is_aux_loc_combined_em_unc_loss: False
is_loc_perception_loss: False
is_loc_repa_loss: False
is_repa_loss: False
is_gen_aux_loss: False

is_action_dit_dense_timestep: True
is_action_dit_projector: True
action_dit_projector_lr: 5.0e-4
action_dit_lr: 1.0e-4
is_aciton_dit_vae_small_init: False

use_pi05_action_dit: True
pi05_pytorch_weight_path: "/home/jiahao/.cache/openpi/openpi-assets/checkpoints/pi05_base"

img_size: 224
use_short_instruction: True

### data
data_dir: "data/preprocessed_data"
train_maps: ['de_dust2','de_ancient','de_nuke']
val_maps: ['de_dust2','de_ancient','de_nuke']
test_maps: ['de_dust2','de_ancient','de_nuke']

### lora
is_lora: True
llm_train_mode: "lora"
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
llm_lora_lr: 1.0e-4

enable_language_model_lora: True
enable_gen_head_lora: False
enable_loc_head_lora: True
freeze_inactive_head: True

fix_vit: True
fix_llm: False
fix_connect: True
fix_dit: True

### optimizer
learning_rate: 1.0e-4
mm_projector_lr: 1.0e-4
weight_decay: 0.0
warmup_ratio: 0.003
lr_scheduler_type: "cosine_with_min_lr"
lr_scheduler_kwargs:
  min_lr: 1.0e-5
